// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Brahma.Helpers")]
[assembly: AssemblyProductAttribute("Brahma.FSharp")]
[assembly: AssemblyDescriptionAttribute("F# quotation to OpenCL translator.")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Brahma.Helpers";
        internal const System.String AssemblyProduct = "Brahma.FSharp";
        internal const System.String AssemblyDescription = "F# quotation to OpenCL translator.";
        internal const System.String AssemblyVersion = "1.0.1";
        internal const System.String AssemblyFileVersion = "1.0.1";
    }
}
